export default [
    {   id: "1",
        img: "/images/1.webp",
        title: "Suraj",
        text: "Retro",
        price: "500",
    },
    {   id: "2",
        img: "/images/2.webp",
        title: "Prasoon",
        text: "Classic",
        price: "500",
    },
    {   id: "3",
        img: "/images/3.webp",
        title: "Suraj",
        text: "Vintage",
        price: "500",
    },
    {   id: "4",
        img: "/images/4.webp",
        title: "Prashant",
        text: "Limited",
        price: "500",
    },
    {   id: "5",
        img: "/images/5.webp",
        title: "Prasoon",
        text: "Classic",
        price: "500",
    },
    {   id: "6",
        img: "/images/6.webp",
        title: "Suraj",
        text: "Classic",
        price: "500",
    },
    {   id: "7",
        img: "/images/7.webp",
        title: "Prashant",
        text: "Vintage",
        price: "500",
    },
    {   id: "8",
        img: "/images/8.webp",
        title: "Suraj",
        text: "Retro",
        price: "500",
    },
]